[package]
name = "AdventofCode22"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "dayone"
path = "src/bin/dayone/main.rs"

[[bin]]
name = "daytwo"
path = "src/bin/daytwo/main.rs"

[dependencies]
